# Generated by Django 6.0.5 on 2026-06-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0002_alter_perfilusuario_options_perfilusuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa', verbose_name='Empresa (solo para roles empresa)'),
        ),
    ]
