# Generated by Django 6.0.7 on 2026-08-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilusuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
