# Generated by Django 6.0.3 on 2026-08-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_apellidos_perfilusuario_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresa/', verbose_name='Logo de la empresa'),
        ),
    ]
