# Generated by Django 6.0.7 on 2026-09-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfilusuario_foto_perfilusuario_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cedula',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], default='CC', max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
