# Generated by Django 6.0.7 on 2026-09-06 05:14

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_perfilusuario_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', validators=[core.validators.validate_file_extension], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresa/', validators=[core.validators.validate_file_extension], verbose_name='Logo de la empresa'),
        ),
    ]
