# Generated by Django 6.0.5 on 2026-06-06 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('pqrs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_radicado', models.CharField(max_length=50, unique=True, verbose_name='Código de Radicado')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Solicitud')),
                ('tipo_detectado', models.CharField(max_length=50, verbose_name='Tipo Detectado por IA')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelta', 'Resuelta')], default='Pendiente', max_length=30, verbose_name='Estado Actual')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Radicación')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa Destino')),
                ('id_usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(verbose_name='Contenido de la Respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('id_pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='pqrs.pqrs', verbose_name='PQRS Asociado')),
                ('id_usuario_responde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Responde')),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
