# Generated by Django 6.0.5 on 2026-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_remove_solicitud_empresa_remove_solicitud_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pqrs_adjuntos/', verbose_name='Archivo adjunto'),
        ),
    ]
