# Generated by Django 6.0.7 on 2026-08-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0004_historialpqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='sentimiento',
            field=models.CharField(blank=True, default='neutral', max_length=20, verbose_name='Sentimiento detectado'),
        ),
    ]
