# Generated by Django 6.0.7 on 2026-08-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0006_chatmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapqrs',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_adjuntos/', verbose_name='Archivo adjunto en respuesta'),
        ),
    ]
