# Generated by Django 6.0.7 on 2026-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0007_respuestapqrs_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='respuestapqrs',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_adjuntos/', verbose_name='Archivo adjunto'),
        ),
    ]
