# Generated by Django 6.0.3 on 2026-08-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0008_pqrs_fecha_cierre_alter_respuestapqrs_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrs',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='respuestapqrs',
            name='archivo',
        ),
    ]
