# Generated by Django 6.0.3 on 2026-08-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0009_remove_pqrs_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapqrs',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_adjuntos/', verbose_name='Archivo adjunto en respuesta'),
        ),
    ]
