# Generated by Django 6.0.3 on 2026-08-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0010_respuestapqrs_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
    ]
