# Generated by Django 6.0.7 on 2026-09-06 05:14

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0012_remove_sentimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pqrs_adjuntos/', validators=[core.validators.validate_file_extension], verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='respuestapqrs',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_adjuntos/', validators=[core.validators.validate_file_extension], verbose_name='Archivo adjunto en respuesta'),
        ),
    ]
