# Generated by Django 6.0.5 on 2026-06-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=50, verbose_name='Nombre del Plan')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('limite_usuarios', models.IntegerField(verbose_name='Límite de Usuarios')),
                ('limite_pqrs', models.IntegerField(verbose_name='Límite de PQRS Mensuales')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT de la Empresa')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.plan', verbose_name='Plan Contratado')),
            ],
        ),
    ]
