# Generated by Django 6.0.7 on 2026-08-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_fin_suscripcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin suscripción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_suscripcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio suscripción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pago_activo',
            field=models.BooleanField(default=False, verbose_name='Pago activo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ref_payco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia ePayco'),
        ),
    ]
